#!/bin/sh
#
# This is a script which using sudo allows a user to verify their own password.
# It is used to avoid a requirement that unprivileged users be able to run /bin/su.
#
# It complies with the requirements of the -unixpw_cmd option of x11vnc.
#
# It takes a user and password on standard input on separate lines.
#

read user
read password

if ! echo $password | sudo -S -g nogroup /bin/true /bin/true 1>/dev/null 2>/dev/null
then
    exit 1
fi

# Kill the caching of credentials.
sudo -K

# At this stage, we know the sudo was successful.
if  [  "X$RFB_UNIXPW_CMD_RUN"  =  "X"  ]
then
    exit  0
fi

# At this point, we know that RFB_UNIXPW_CMD_RUN is set, so we run it.
sh -c "$RFB_UNIXPW_CMD_RUN"
